
# spring.profiles.active: dev
spring:
    # config:
    #     activate:
    #         on-profile: dev
    datasource:
        url: jdbc:postgresql://127.0.0.1:3306/coffeeshop
        username: postgres 
        password: postgres
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQL94Dialect
